{% set name = "supervisor" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a2bf149adf42997e1bb44b70c43b613275ec9852c3edacca86a9166b27e945e

build:
  number: 0
  skip: true  # [win]
  entry_points:
    - supervisord = supervisor.supervisord:main
    - supervisorctl = supervisor.supervisorctl:main
    - echo_supervisord_conf = supervisor.confecho:main
    - pidproxy = supervisor.pidproxy:main

requirements:
  host:
    - gettext
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - setuptools
  
{% set ignore_tests = "" %}
# PermissionError: [Errno 13] Permission denied: '/tmp/foo'
{% set ignore_tests = ignore_tests + " --ignore=supervisor/tests/test_dispatchers.py" %}  # [linux] 

test:
  requires:
    - pip
    - pytest >=2.5.2
    - mock >=0.5.0
  source_files:
    - supervisor/tests
  commands:
    - pip check
    - py.test supervisor/tests {{ ignore_tests }}
    - supervisord -h
    - supervisorctl -h
    - echo_supervisord_conf -h
  imports:
    - supervisor

about:
  home: http://supervisord.org/
  license: BSD-3-Clause-Modification AND BSD-3-Clause AND PSF-2.0
  license_file: LICENSES.txt
  license_family: BSD
  summary: A Process Control System
  description: |
    Supervisor is a client/server system that allows its users to monitor and
    control a number of processes on UNIX-like operating systems.
  doc_url: http://supervisord.org/
  dev_url: https://github.com/Supervisor/supervisor

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
