{% set name = "supervisor" %}
{% set version = "3.3.4" %}
{% set sha256 = "212201a3fd1d35c150ef0c35bf0676fd1a6c195fb60bf0f2147fe7dbd317e672" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py3k]

requirements:
  build:
    - gettext
    - python
    - setuptools

  run:
    - python
    - meld3 >=1

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
  source_files:
    - supervisor/tests/
  commands:
    - py.test supervisor/tests/
    - supervisord
    - supervisorctl status
    - supervisorctl shutdown

about:
  home: http://supervisord.org/
  license: BSD-derived
  license_file: LICENSES.txt
  license_family: BSD
  summary: A Process Control System
  description: |
    Supervisor is a client/server system that allows its users to monitor and
    control a number of processes on UNIX-like operating systems.
  doc_url: http://supervisord.org/
  doc_source_url: https://github.com/Supervisor/supervisor
  dev_url: https://github.com/Supervisor/supervisor

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
