{% set name = "supervisor" %}
{% set version = "3.3.2" %}
{% set sha256 = "bbb870f5b59c5c4fd79f711553e343158b2c64688997a23a1bcb2ce643f57771" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py3k]

requirements:
  build:
    - gettext
    - python
    - setuptools

  run:
    - python
    - meld3 >=1

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
  source_files:
    - supervisor/tests/
  commands:
    - py.test supervisor/tests/
    - supervisord
    - supervisorctl status
    - supervisorctl shutdown

about:
  home: https://github.com/Supervisor/supervisor
  license: BSD 3-clause
  summary: Supervisor process control system for UNIX

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
