{% set name = "supervisor" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3268709d7e3d4e728f88fd06a29215916e1e59ff5fad5fead9de856df6f98382

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - gettext
    - python
    - setuptools

  run:
    - python
    - meld3 >=1

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
    - sed  # [osx]
  source_files:
    - supervisor/tests/
  commands:
    - py.test supervisor/tests/
    - sed -i 's@^serverurl=.*@serverurl=unix:///tmp/supervisord.sock@' ${CONDA_PREFIX}/etc/supervisord.conf
    - sed -i 's@^file=.*@file=/tmp/supervisord.sock@' ${CONDA_PREFIX}/etc/supervisord.conf
    - supervisord
    - supervisorctl status
    - supervisorctl shutdown

about:
  home: https://github.com/Supervisor/supervisor
  license: ZPL-variant
  license_family: Other
  summary: Supervisor process control system for UNIX

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
