{% set name = "supervisor" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dc86fe0476e945e61483d614ceb2cf4f93b95282eb243bdf792621994360383

build:
  number: 1
  skip: true  # [win]

requirements:
  host:
    - gettext
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
  source_files:
    - supervisor/tests/
  commands:
    - py.test supervisor/tests/
    - supervisord -h
    - supervisorctl -h
    - echo_supervisord_conf -h
  imports:
    - supervisor

about:
  home: http://supervisord.org/
  license: BSD-derived
  license_file: LICENSES.txt
  license_family: BSD
  summary: A Process Control System
  description: |
    Supervisor is a client/server system that allows its users to monitor and
    control a number of processes on UNIX-like operating systems.
  doc_url: http://supervisord.org/
  doc_source_url: https://github.com/Supervisor/supervisor
  dev_url: https://github.com/Supervisor/supervisor

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
