{% set name = "supervisor" %}
{% set version = "3.3.3" %}
{% set sha256 = "96287ebfabf9a6923f74123b056c4da39c617fef367980f007cac02fba6527ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win or py3k]

requirements:
  build:
    - gettext
    - python
    - setuptools

  run:
    - python
    - meld3 >=1

test:
  requires:
    - pytest >=2.5.2
    - mock >=0.5.0
  source_files:
    - supervisor/tests/
  commands:
    - py.test supervisor/tests/
    - supervisord
    - supervisorctl status
    - supervisorctl shutdown

about:
  home: https://github.com/Supervisor/supervisor
  license: ZPL-variant
  license_family: Other
  summary: Supervisor process control system for UNIX

extra:
  recipe-maintainers:
    - kalefranz
    - sodre
