travis:
  secure:
    BINSTAR_TOKEN: eAOLYAIJnULpm2PRFNJmKsJnLSAOpxjjPf68LrQ2Rs12QKHp3FB99qZ80GHVspxjQ1Pyif/E0m/hrZa+FS9OeYxbt3BdAQiefm+buB5bohS/PNRdatcMvjC2P4O1tNTEgC4FdHL7P+HB5DHQNV/xcOY59cF7uHflJJ2NPrO48myBRKqxzEzyvVQV3VjHSB7+RXoAQAh3xN3bJWEavK+w398DrpQx/Clu+HWha2Hf3Nu8O/tJGAEQZ4hpsJbqM56hALruY8kKH1IuIZJEYFHkyEG+xKWRBCnrHrasESIFSNjZS+lnynjSLsGI1wHwWmx1XIs2ssMHxrpXtShKnr5D7h2ihQHN+2Ab/n4BxAQAEzgfIKH8M3QMYK/a0bTkw4tKLmZKK9mgjI+9WoGvcEEh2c9MXntkmg1+1Hq8KpBBkoX1e7ATa/DsEygqXJDaeGv7xOoq7J+sxmnBrKGjYcJwzPlUJfJ6CiQjaj/A1MUfT14qOd1lDoizm83cZy/LlLUWXqdFbBfaV987XPgUPMmXuVp8PGogOqHRjmRN1Bu9Ey2KVZk9IZnoPz713uaopstig8mgLwy1xW66GvLpwb6+RWLAVJnCoDQ3wI0tTbw4FuvK6xWX8rdeuxS77DiFtEMJGTASXTgq9XXh+CJoGPNd2hSUwKH9SToEC3bs+IcXxeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
