travis:
  secure:
    BINSTAR_TOKEN: ampnJlCOl2oO5QMyTgaXQTLln9E3mvaZgqgmOrJiHRuiPlTXgAEfvTQ9iiHG9RMcC/NNZVMB1qWoetSv7v/OTqjNBvvI0QEjjb+KsnJg/pWBpPbwlqCmTerA4Umk5/KH44jWE5wP6ABfrXoiKlIQP9OHaSk0kByTz8gD/63te9BuvjFaC9Z2oyv9blvGWGaKIhFJdCvsoiqQcoFpYKMq1VGxcF/nYNQNMorfQPe2ean7iG5HBCVIoSdmf/HRNLU/tDmANAnPopfeEbxcJhMNE+J6Qp/Hz+/gQ9eiK43EcYROcfLE7BBaVbI8h6PGpy8Bxxy5Ao8dCc7X7r4qknmVg2dPRNg4fCoIQm4KTo4owbUJoj8odhcpd0QGtM80S7wztvKMjZpNrJVbPuG2bAf5rPBKI2Grx5l0z2GvWUAS7BRKXy9G3+D1YSXO9wGbd+e/ixPTo36obakiBiFNqGl5g7PjTUK0c+YeGwZQB5U70lsdQnwWuMl0asCSoHzDr7Ys7Gvd+DzqU0w/AvHE5W2YXgcqQsC0onNvf7ULVwZm2EJTuOPNpWgpdi+vu5L2SUGQG8xmM2yq+unuoRbk4Nr+vc9UWupQQapb5Qiln3Hcgq3W85lD7JdHZaliPcVdn/7+hNEgUf9Np782G3AEafFXP4HSwEClIyCZnB2SIMOMYHs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
